/*
 * This file is generated by jOOQ.
 */
package com.marcinmilewski.db.keys


import com.marcinmilewski.db.tables.Payments
import com.marcinmilewski.db.tables.records.PaymentsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val PAYMENTS_PKEY: UniqueKey<PaymentsRecord> = Internal.createUniqueKey(Payments.PAYMENTS, DSL.name("payments_pkey"), arrayOf(Payments.PAYMENTS.ID), true)
