mutation Payment {
    payment(
        request: {
            customerId: "12345",
            price: "200.50",
            priceModifier: 1.00,
            paymentMethod: "BANK_TRANSFER",
            datetime: "2022-03-01T01:00:00Z",
            additionalItem: {accountNumber: "123456789"}
        }) {
        finalPrice
        points
    }
}