mutation Payment {
    payment(
        request: {
            customerId: "12345",
            price: "200.50",
            priceModifier: 0.8,
            paymentMethod: "CASH",
            datetime: "2022-03-01T01:00:00Z",
            additionalItem: {}
        }) {
        finalPrice
        points
    }
}
