/*
 * This file is generated by jOOQ.
 */
package com.marcinmilewski.db.tables.references


import com.marcinmilewski.db.tables.Payments



/**
 * The table <code>public.payments</code>.
 */
val PAYMENTS: Payments = Payments.PAYMENTS
