/*
 * This file is generated by jOOQ.
 */
package com.marcinmilewski.db.tables


import com.marcinmilewski.db.Public
import com.marcinmilewski.db.indexes.IDX_PAYMENTS_DATETIME
import com.marcinmilewski.db.keys.PAYMENTS_PKEY
import com.marcinmilewski.db.tables.records.PaymentsRecord

import java.math.BigDecimal
import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Payments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PaymentsRecord>?,
    parentPath: InverseForeignKey<out Record, PaymentsRecord>?,
    aliased: Table<PaymentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PaymentsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.payments</code>
         */
        val PAYMENTS: Payments = Payments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PaymentsRecord> = PaymentsRecord::class.java

    /**
     * The column <code>public.payments.id</code>.
     */
    val ID: TableField<PaymentsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.payments.customer_id</code>.
     */
    val CUSTOMER_ID: TableField<PaymentsRecord, String?> = createField(DSL.name("customer_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.payments.price</code>.
     */
    val PRICE: TableField<PaymentsRecord, BigDecimal?> = createField(DSL.name("price"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "")

    /**
     * The column <code>public.payments.final_price</code>.
     */
    val FINAL_PRICE: TableField<PaymentsRecord, BigDecimal?> = createField(DSL.name("final_price"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "")

    /**
     * The column <code>public.payments.points</code>.
     */
    val POINTS: TableField<PaymentsRecord, BigDecimal?> = createField(DSL.name("points"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "")

    /**
     * The column <code>public.payments.payment_method</code>.
     */
    val PAYMENT_METHOD: TableField<PaymentsRecord, String?> = createField(DSL.name("payment_method"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.payments.datetime</code>.
     */
    val DATETIME: TableField<PaymentsRecord, LocalDateTime?> = createField(DSL.name("datetime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.payments.additional_item</code>.
     */
    val ADDITIONAL_ITEM: TableField<PaymentsRecord, JSONB?> = createField(DSL.name("additional_item"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.payments.created_at</code>.
     */
    val CREATED_AT: TableField<PaymentsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.payments.updated_at</code>.
     */
    val UPDATED_AT: TableField<PaymentsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PaymentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PaymentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PaymentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.payments</code> table reference
     */
    constructor(): this(DSL.name("payments"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_PAYMENTS_DATETIME)
    override fun getIdentity(): Identity<PaymentsRecord, Int?> = super.getIdentity() as Identity<PaymentsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PaymentsRecord> = PAYMENTS_PKEY
    override fun `as`(alias: String): Payments = Payments(DSL.name(alias), this)
    override fun `as`(alias: Name): Payments = Payments(alias, this)
    override fun `as`(alias: Table<*>): Payments = Payments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Payments = Payments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Payments = Payments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Payments = Payments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Payments = Payments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Payments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Payments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Payments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Payments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Payments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Payments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Payments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Payments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Payments = where(DSL.notExists(select))
}
