/*
 * This file is generated by jOOQ.
 */
package com.marcinmilewski.db.indexes


import com.marcinmilewski.db.tables.Payments

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_PAYMENTS_DATETIME: Index = Internal.createIndex(DSL.name("idx_payments_datetime"), Payments.PAYMENTS, arrayOf(Payments.PAYMENTS.DATETIME), false)
